# Generated by Django 5.1.1 on 2025-01-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
